export const CATEGORIES = [
  { slug: "servicios-de-plomeria", displayName: "Servicios de plomería" },
  {
    slug: "servicios-de-electricidad",
    displayName: "Servicios de electricidad",
  },
  { slug: "servicios-de-cerrajeria", displayName: "Servicios de cerrajería" },
  {
    slug: "servicios-de-climatizacion",
    displayName: "Servicios de climatización",
  },
  { slug: "servicios-de-pintura", displayName: "Servicios de pintura" },
  { slug: "servicios-de-carpinteria", displayName: "Servicios de carpintería" },
  {
    slug: "reparacion-de-electrodomesticos",
    displayName: "Reparación de electrodomésticos",
  },
  { slug: "tecnicos-de-laptops", displayName: "Técnicos de laptops" },
  { slug: "tecnicos-de-celulares", displayName: "Técnicos de celulares" },
  { slug: "tecnicos-de-redes", displayName: "Técnicos de redes" },
  { slug: "servicios-de-jardineria", displayName: "Servicios de jardinería" },
  { slug: "limpieza-domestica", displayName: "Limpieza doméstica" },
  { slug: "limpieza-industrial", displayName: "Limpieza industrial" },
  { slug: "servicios-de-mudanza", displayName: "Servicios de mudanza" },
  { slug: "mensajeria-expres", displayName: "Mensajería exprés" },
  { slug: "catering-a-domicilio", displayName: "Catering a domicilio" },
  { slug: "pasteleria-personalizada", displayName: "Pastelería personalizada" },
  { slug: "organizacion-de-eventos", displayName: "Organización de eventos" },
  { slug: "fotografia-profesional", displayName: "Fotografía profesional" },
  { slug: "produccion-audiovisual", displayName: "Producción audiovisual" },
  { slug: "diseno-grafico", displayName: "Diseño gráfico" },
  { slug: "diseno-web", displayName: "Diseño web" },
  { slug: "desarrollo-de-software", displayName: "Desarrollo de software" },
  { slug: "marketing-digital", displayName: "Marketing digital" },
  {
    slug: "gestion-de-redes-sociales",
    displayName: "Gestión de redes sociales",
  },
  { slug: "seo-y-sem", displayName: "SEO y SEM" },
  { slug: "consultoria-de-negocios", displayName: "Consultoría de negocios" },
  { slug: "asesoria-legal", displayName: "Asesoría legal" },
  { slug: "servicios-contables", displayName: "Servicios contables" },
  { slug: "asesoria-financiera", displayName: "Asesoría financiera" },
  {
    slug: "gestion-de-recursos-humanos",
    displayName: "Gestión de recursos humanos",
  },
  { slug: "entrenamiento-personal", displayName: "Entrenamiento personal" },
  { slug: "clases-de-yoga", displayName: "Clases de yoga" },
  { slug: "clases-de-pilates", displayName: "Clases de pilates" },
  { slug: "clases-de-baile", displayName: "Clases de baile" },
  { slug: "clases-de-musica", displayName: "Clases de música" },
  { slug: "clases-de-idiomas", displayName: "Clases de idiomas" },
  { slug: "clases-de-matematicas", displayName: "Clases de matemáticas" },
  { slug: "clases-de-ciencias", displayName: "Clases de ciencias" },
  { slug: "tutorias-escolares", displayName: "Tutorías escolares" },
  { slug: "coaching-profesional", displayName: "Coaching profesional" },
  { slug: "psicoterapia", displayName: "Psicoterapia" },
  { slug: "fisioterapia-a-domicilio", displayName: "Fisioterapia a domicilio" },
  { slug: "masajes-terapeuticos", displayName: "Masajes terapéuticos" },
  { slug: "peluqueria-a-domicilio", displayName: "Peluquería a domicilio" },
  { slug: "barberia-a-domicilio", displayName: "Barbería a domicilio" },
  { slug: "maquillaje-profesional", displayName: "Maquillaje profesional" },
  { slug: "manicura-y-pedicura", displayName: "Manicura y pedicura" },
  { slug: "estilismo-personal", displayName: "Estilismo personal" },
  {
    slug: "atencion-medica-domiciliaria",
    displayName: "Atención médica domiciliaria",
  },
  { slug: "enfermeria-a-domicilio", displayName: "Enfermería a domicilio" },
  {
    slug: "cuidado-de-adultos-mayores",
    displayName: "Cuidado de adultos mayores",
  },
  { slug: "cuidado-infantil", displayName: "Cuidado infantil" },
  { slug: "paseo-de-mascotas", displayName: "Paseo de mascotas" },
  { slug: "peluqueria-canina", displayName: "Peluquería canina" },
  {
    slug: "adiestramiento-de-mascotas",
    displayName: "Adiestramiento de mascotas",
  },
  { slug: "veterinaria-a-domicilio", displayName: "Veterinaria a domicilio" },
  { slug: "seguridad-privada", displayName: "Seguridad privada" },
  { slug: "instalacion-de-alarmas", displayName: "Instalación de alarmas" },
  {
    slug: "consultoria-en-iluminacion",
    displayName: "Consultoría en iluminación",
  },
  { slug: "diseno-de-interiores", displayName: "Diseño de interiores" },
  { slug: "decoracion-de-espacios", displayName: "Decoración de espacios" },
  { slug: "organizacion-de-oficinas", displayName: "Organización de oficinas" },
  { slug: "traduccion-profesional", displayName: "Traducción profesional" },
  {
    slug: "redaccion-y-correccion-de-textos",
    displayName: "Redacción y corrección de textos",
  },
  { slug: "asistente-virtual", displayName: "Asistente virtual" },
  {
    slug: "soporte-tecnico-informatico",
    displayName: "Soporte técnico informático",
  },
  {
    slug: "mantenimiento-de-servidores",
    displayName: "Mantenimiento de servidores",
  },
  {
    slug: "desarrollo-de-apps-moviles",
    displayName: "Desarrollo de apps móviles",
  },
  {
    slug: "gestion-de-bases-de-datos",
    displayName: "Gestión de bases de datos",
  },
  { slug: "servicios-de-hosting", displayName: "Servicios de hosting" },
  { slug: "registro-de-dominios", displayName: "Registro de dominios" },
  {
    slug: "administracion-de-sistemas",
    displayName: "Administración de sistemas",
  },
  {
    slug: "automatizacion-de-procesos",
    displayName: "Automatización de procesos",
  },
  { slug: "robotica-educativa", displayName: "Robótica educativa" },
  { slug: "diseno-de-productos", displayName: "Diseño de productos" },
  { slug: "consultoria-energetica", displayName: "Consultoría energética" },
  {
    slug: "instalacion-de-paneles-solares",
    displayName: "Instalación de paneles solares",
  },
  { slug: "inspeccion-electrica", displayName: "Inspección eléctrica" },
  { slug: "inspeccion-de-gas", displayName: "Inspección de gas" },
  {
    slug: "mantenimiento-de-piscinas",
    displayName: "Mantenimiento de piscinas",
  },
  {
    slug: "impermeabilizacion-de-techos",
    displayName: "Impermeabilización de techos",
  },
  { slug: "albanileria-general", displayName: "Albañilería general" },
  { slug: "remodelacion-de-baños", displayName: "Remodelación de baños" },
  { slug: "remodelacion-de-cocinas", displayName: "Remodelación de cocinas" },
  {
    slug: "ventanas-y-puertas-de-aluminio",
    displayName: "Ventanas y puertas de aluminio",
  },
  { slug: "vidrieria-y-cristaleria", displayName: "Vidriería y cristalería" },
  {
    slug: "colocacion-de-ceramica-y-baldosas",
    displayName: "Colocación de cerámica y baldosas",
  },
  {
    slug: "topografia-y-levantamientos",
    displayName: "Topografía y levantamientos",
  },
  { slug: "dron-y-fotogrametria", displayName: "Dron y fotogrametría" },
  {
    slug: "inspeccion-de-estructuras",
    displayName: "Inspección de estructuras",
  },
  { slug: "edicion-de-video", displayName: "Edición de video" },
  { slug: "animacion-2d-3d", displayName: "Animación 2D/3D" },
  {
    slug: "arquitectura-y-obra-civil",
    displayName: "Arquitectura y obra civil",
  },
  { slug: "ingenieria-mecanica", displayName: "Ingeniería mecánica" },
  { slug: "ingenieria-electrica", displayName: "Ingeniería eléctrica" },
  { slug: "ingenieria-civil", displayName: "Ingeniería civil" },
  {
    slug: "consultoria-en-sustentabilidad",
    displayName: "Consultoría en sustentabilidad",
  },
  { slug: "diseno-ux-ui", displayName: "Diseño UX/UI" },
  { slug: "testing-de-software", displayName: "Testing de software" },
  {
    slug: "servicios-de-mecanica-automotriz",
    displayName: "Servicios de mecánica automotriz",
  },
  {
    slug: "servicios-de-mecanica-de-motocicletas",
    displayName: "Servicios de mecánica de motocicletas",
  },
  {
    slug: "servicios-de-mecanica-de-bicicletas",
    displayName: "Servicios de mecánica de bicicletas",
  },
  {
    slug: "servicios-de-transporte-de-pasajeros",
    displayName: "Servicios de transporte de pasajeros",
  },
  {
    slug: "servicios-de-transporte-de-carga",
    displayName: "Servicios de transporte de carga",
  },
  { slug: "clases-de-cocina", displayName: "Clases de cocina" },
  { slug: "clases-de-reposteria", displayName: "Clases de repostería" },
  { slug: "clases-de-arte", displayName: "Clases de arte" },
  {
    slug: "clases-de-pintura-artistica",
    displayName: "Clases de pintura artística",
  },
  { slug: "clases-de-escultura", displayName: "Clases de escultura" },
  { slug: "taller-de-ceramica", displayName: "Taller de cerámica" },
  {
    slug: "taller-de-carpinteria-diy",
    displayName: "Taller de carpintería (DIY)",
  },
  {
    slug: "clases-de-fotografia-basica",
    displayName: "Clases de fotografía básica",
  },
  {
    slug: "clases-de-edicion-de-video",
    displayName: "Clases de edición de video",
  },
  { slug: "clases-de-diseno-de-moda", displayName: "Clases de diseño de moda" },
  { slug: "servicios-de-modista", displayName: "Servicios de modista" },
  {
    slug: "servicios-de-sastreria-a-medida",
    displayName: "Servicios de sastrería a medida",
  },
  {
    slug: "confeccion-de-ropa-personalizada",
    displayName: "Confección de ropa personalizada",
  },
  {
    slug: "servicios-de-costura-y-arreglos",
    displayName: "Servicios de costura y arreglos",
  },
  { slug: "arreglo-de-calzado", displayName: "Arreglo de calzado" },
  {
    slug: "reparacion-de-bolsos-y-carteras",
    displayName: "Reparación de bolsos y carteras",
  },
  {
    slug: "restauracion-de-muebles-antiguos",
    displayName: "Restauración de muebles antiguos",
  },
  {
    slug: "tapiceria-y-recubrimiento-de-muebles",
    displayName: "Tapicería y recubrimiento de muebles",
  },
  {
    slug: "servicios-de-herreria-artesanal",
    displayName: "Servicios de herrería artesanal",
  },
  { slug: "servicios-de-soldadura", displayName: "Servicios de soldadura" },
  { slug: "forja-artistica", displayName: "Forja artística" },
  { slug: "impresion-3d", displayName: "Impresión 3D" },
  { slug: "corte-laser", displayName: "Corte láser" },
  { slug: "cnc-y-fresado", displayName: "CNC y fresado" },
  {
    slug: "servicios-de-prototipado-rapido",
    displayName: "Servicios de prototipado rápido",
  },
  { slug: "diseno-cad-cae", displayName: "Diseño CAD/CAE" },
  { slug: "home-staging", displayName: "Home staging (puesta en escena)" },
  {
    slug: "inspeccion-y-tasacion-de-propiedades",
    displayName: "Inspección y tasación de propiedades",
  },
  { slug: "corretaje-inmobiliario", displayName: "Corretaje inmobiliario" },
  { slug: "gestion-de-alquileres", displayName: "Gestión de alquileres" },
  {
    slug: "administracion-de-condominios",
    displayName: "Administración de condominios",
  },
  {
    slug: "asesoria-en-credito-hipotecario",
    displayName: "Asesoría en crédito hipotecario",
  },
  { slug: "mudanza-internacional", displayName: "Mudanza internacional" },
  {
    slug: "almacenamiento-y-bodegaje",
    displayName: "Almacenamiento y bodegaje",
  },
  { slug: "courier-internacional", displayName: "Courier internacional" },
  { slug: "logistica-y-distribucion", displayName: "Logística y distribución" },
  { slug: "gestion-de-inventarios", displayName: "Gestión de inventarios" },
  { slug: "empaquetado-profesional", displayName: "Empaquetado profesional" },
  { slug: "seguridad-informatica", displayName: "Seguridad informática" },
  {
    slug: "pentesting-y-auditoria-de-seguridad",
    displayName: "Pentesting y auditoría de seguridad",
  },
  {
    slug: "implementacion-de-firewalls",
    displayName: "Implementación de firewalls",
  },
  { slug: "configuracion-de-vpn", displayName: "Configuración de VPN" },
  {
    slug: "consultoria-en-ciberseguridad",
    displayName: "Consultoría en ciberseguridad",
  },
  {
    slug: "backup-y-recuperacion-de-datos",
    displayName: "Backup y recuperación de datos",
  },
  { slug: "monitoreo-de-redes", displayName: "Monitoreo de redes" },
  {
    slug: "helpdesk-y-soporte-remoto",
    displayName: "Helpdesk y soporte remoto",
  },
  {
    slug: "migracion-de-bases-de-datos",
    displayName: "Migración de bases de datos",
  },
  { slug: "servicios-devops", displayName: "Servicios DevOps" },
  { slug: "configuracion-de-ci-cd", displayName: "Configuración de CI/CD" },
  {
    slug: "contenerizacion-con-docker",
    displayName: "Contenerización con Docker",
  },
  {
    slug: "orquestacion-con-kubernetes",
    displayName: "Orquestación con Kubernetes",
  },
  {
    slug: "gestion-de-clusters-de-contenedores",
    displayName: "Gestión de clusters de contenedores",
  },
  {
    slug: "arquitectura-en-la-nube-aws-azure-gcp",
    displayName: "Arquitectura en la nube (AWS/Azure/GCP)",
  },
  {
    slug: "consultoria-cloud-computing",
    displayName: "Consultoría cloud computing",
  },
  { slug: "servicios-de-cdn", displayName: "Servicios de CDN" },
  { slug: "integracion-de-apis", displayName: "Integración de APIs" },
  {
    slug: "desarrollo-de-microservicios",
    displayName: "Desarrollo de microservicios",
  },
  { slug: "testing-automatizado", displayName: "Testing automatizado" },
  { slug: "qa-manual", displayName: "QA manual" },
  { slug: "qa-de-performance", displayName: "QA de performance" },
  { slug: "qa-de-seguridad", displayName: "QA de seguridad" },
  {
    slug: "testing-de-compatibilidad",
    displayName: "Testing de compatibilidad",
  },
  {
    slug: "servicios-de-accesibilidad-web",
    displayName: "Servicios de accesibilidad web",
  },
  { slug: "consultoria-seo-tecnico", displayName: "Consultoría SEO técnico" },
  { slug: "analisis-de-datos", displayName: "Análisis de datos" },
  {
    slug: "visualizacion-de-datos-power-bi-tableau",
    displayName: "Visualización de datos (Power BI/Tableau)",
  },
  { slug: "bi-y-reporting", displayName: "BI y reporting" },
  { slug: "consultoria-big-data", displayName: "Consultoría Big Data" },
  { slug: "machine-learning", displayName: "Machine Learning" },
  { slug: "inteligencia-artificial", displayName: "Inteligencia Artificial" },
  {
    slug: "ia-conversacional-chatbots",
    displayName: "IA conversacional (chatbots)",
  },
  { slug: "desarrollo-de-chatbots", displayName: "Desarrollo de chatbots" },
  { slug: "desarrollo-de-voicebots", displayName: "Desarrollo de voicebots" },
  { slug: "skills-para-alexa-google", displayName: "Skills para Alexa/Google" },
  {
    slug: "blockchain-y-smart-contracts",
    displayName: "Blockchain y smart contracts",
  },
  {
    slug: "consultoria-en-criptomonedas",
    displayName: "Consultoría en criptomonedas",
  },
  { slug: "desarrollo-de-dapps", displayName: "Desarrollo de dApps" },
  { slug: "nft-development", displayName: "NFT development" },
  { slug: "staking-de-criptomonedas", displayName: "Staking de criptomonedas" },
  { slug: "lending-crypto", displayName: "Lending crypto" },
  {
    slug: "auditoria-de-smart-contracts",
    displayName: "Auditoría de smart contracts",
  },
  { slug: "trading-algoritmico", displayName: "Trading algorítmico" },
  { slug: "soporte-de-wallets", displayName: "Soporte de wallets" },
  { slug: "ux-research", displayName: "UX Research" },
  {
    slug: "diseno-de-experiencia-de-usuario-ux",
    displayName: "Diseño de experiencia de usuario (UX)",
  },
  {
    slug: "diseno-de-interaccion-ixd",
    displayName: "Diseño de interacción (IxD)",
  },
  {
    slug: "arquitectura-de-informacion",
    displayName: "Arquitectura de información",
  },
  { slug: "design-systems", displayName: "Design systems" },
  {
    slug: "prototipado-interactivo-figma",
    displayName: "Prototipado interactivo (Figma)",
  },
  { slug: "animacion-ui-lottie", displayName: "Animación UI (Lottie)" },
  { slug: "copywriting-digital", displayName: "Copywriting digital" },
  { slug: "voice-over-y-locuciones", displayName: "Voice-over y locuciones" },
  {
    slug: "subtitulado-y-transcripcion",
    displayName: "Subtitulado y transcripción",
  },
  { slug: "narracion-de-audiolibros", displayName: "Narración de audiolibros" },
  { slug: "servicios-de-doblaje", displayName: "Servicios de doblaje" },
] as const;

export type CategorySlug = (typeof CATEGORIES)[number]["slug"];
export type Category = (typeof CATEGORIES)[number]["displayName"];
