// src/config/districts.ts

export const DISTRICTS = [
  { slug: "ancon", displayName: "Ancón" },
  { slug: "ate", displayName: "Ate" },
  { slug: "barranco", displayName: "Barranco" },
  { slug: "brena", displayName: "Breña" },
  { slug: "carabayllo", displayName: "Carabayllo" },
  { slug: "chaclacayo", displayName: "Chaclacayo" },
  { slug: "chorrillos", displayName: "Chorrillos" },
  { slug: "cieneguilla", displayName: "Cieneguilla" },
  { slug: "comas", displayName: "Comas" },
  { slug: "el-agustino", displayName: "El Agustino" },
  { slug: "independencia", displayName: "Independencia" },
  { slug: "jesus-maria", displayName: "Jesús María" },
  { slug: "la-molina", displayName: "La Molina" },
  { slug: "la-victoria", displayName: "La Victoria" },
  { slug: "lima", displayName: "Lima" },
  { slug: "lince", displayName: "Lince" },
  { slug: "los-olivos", displayName: "Los Olivos" },
  { slug: "lurin", displayName: "Lurín" },
  { slug: "magdalena-del-mar", displayName: "Magdalena del Mar" },
  { slug: "miraflores", displayName: "Miraflores" },
  { slug: "pachacamac", displayName: "Pachacámac" },
  { slug: "pucusana", displayName: "Pucusana" },
  { slug: "pueblo-libre", displayName: "Pueblo Libre" },
  { slug: "puente-piedra", displayName: "Puente Piedra" },
  { slug: "punta-hermosa", displayName: "Punta Hermosa" },
  { slug: "punta-negra", displayName: "Punta Negra" },
  { slug: "rimac", displayName: "Rímac" },
  { slug: "san-bartolo", displayName: "San Bartolo" },
  { slug: "san-borja", displayName: "San Borja" },
  { slug: "san-isidro", displayName: "San Isidro" },
  { slug: "san-juan-de-lurigancho", displayName: "San Juan de Lurigancho" },
  { slug: "san-juan-de-miraflores", displayName: "San Juan de Miraflores" },
  { slug: "san-luis", displayName: "San Luis" },
  { slug: "san-martin-de-porres", displayName: "San Martín de Porres" },
  { slug: "san-miguel", displayName: "San Miguel" },
  { slug: "santa-anita", displayName: "Santa Anita" },
  { slug: "santa-maria-del-mar", displayName: "Santa María del Mar" },
  { slug: "santa-rosa", displayName: "Santa Rosa" },
  { slug: "santiago-de-surco", displayName: "Santiago de Surco" },
  { slug: "surquillo", displayName: "Surquillo" },
  { slug: "villa-el-salvador", displayName: "Villa El Salvador" },
  { slug: "villa-maria-del-triunfo", displayName: "Villa María del Triunfo" },
];
